import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: 'rgb(57,62,70)',
    borderBottomLeftRadius: 231,
    borderTopRightRadius: 100,
    alignItems: 'center',
  },
  loadingBackground: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    width: '100%',
    backgroundColor: 'rgb(57,62,70)',
  },
  rectangleOfLoadingTop: {
    left: '-14%',
    top: '-17%',
    position: 'absolute',
    // height: 95,
    // width: 248,
    width: '80%',
    height: '30%',
    backgroundColor: 'rgb(0,173,181)',
    transform: [{rotate: '-30deg'}],
    borderBottomLeftRadius: 100,
  },
  firstLoadingImage: {
    width: '41%',
    height: '25%',
    resizeMode: 'stretch',
  },
  rectangleOfLoadingBottom: {
    width: '80%',
    height: '30%',
    backgroundColor: 'rgb(0,173,181)',
    position: 'absolute',
    right: '-14%',
    bottom: '-17%',
    borderTopRightRadius: 100,
    transform: [{rotate: '-30deg'}],
  },
  signUp: {
    marginTop: '1%',
    width: '25.8%',
    height: '15%',
    resizeMode: 'stretch',
  },
  forgetPassword: {
    color: 'white',
    fontSize: 16,
    opacity: 0.4,
    fontWeight: '700',
  },
  greenPartDownPage: {
    backgroundColor: 'rgb(0,173,181)',
    width: '100%',
    height: '47%',
    position: 'absolute',
    bottom: 0,
    borderTopRightRadius: 80,
    borderTopLeftRadius: 80,
    borderBottomLeftRadius: 220,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(0,0,0, 0.4)',
  },
  secondLoadingImage: {
    width: '50%',
    height: '40%',
    resizeMode: 'stretch',
  },
});
