import {StyleSheet} from 'react-native';
import Colors from '../colors';

export default StyleSheet.create({
  rectangleOfTop: {
    backgroundColor: Colors.topColor(),
    width: '120%',
    height: '28%',
    transform: [{rotate: '-22deg'}],
    borderBottomLeftRadius: 75,
    position: 'absolute',
    left: '-7%',
    top: '-18%',
    borderWidth: 1,
    borderColor: 'black',
  },
  rectangleOfBottom: {
    backgroundColor: Colors.topColor(),
    width: '120%',
    height: '28%',
    transform: [{rotate: '-22deg'}],
    borderTopRightRadius: 75,
    position: 'absolute',
    right: '-7%',
    bottom: '-18%',
    borderWidth: 1,
    borderColor: 'black',
  },
  square: {
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginTop: '43%',
    width: '80.8%',
    height: '37.3%',
    borderWidth: 2,
    borderColor: Colors.topColor(),
    borderRadius: 25,
    marginBottom: '6%',
  },
  styleOfImage: {
    width: '28%',
    height: '17%',
    resizeMode: 'stretch',
  },
  contactTextStyle: {
    fontFamily: 'IranSans',
    fontSize: 17,
    color: 'rgb(57,62,70)',
  },
  contactEmailStyle: {
    fontFamily: 'Samim',
    fontWeight: 'bold',
    fontSize: 20,
    color: 'rgb(34,40,49)',
  },
  contactUsStyle: {flex: 1, alignItems: 'center'},
  topPartOfSuggestionPage: {
    height: '10%',
    width: '100%',
    backgroundColor: Colors.topColor(),
    borderBottomRightRadius: 100,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderColor: Colors.borderTopColor(),
  },
  bottomPartOfSuggestionPage: {
    borderWidth: 1,
    borderColor: Colors.borderTopColor(),
    position: 'absolute',
    bottom: 0,
    height: '10%',
    width: '100%',
    backgroundColor: Colors.topColor(),
    borderTopLeftRadius: 100,
  },
  suggestionBackgroundImage: {
    width: '100%',
    height: '90%',
    resizeMode: 'stretch',
    alignItems: 'center',
  },
  textOfSuggestion: {
    fontFamily: 'IranSans',
    marginLeft: '60%',
    fontSize: 25,
    marginTop: '26%',
  },
  animatedTextStyle: {
    color: Colors.accent(),
    position: 'absolute',
    top: '40%',
    left: '35%',
    fontFamily: 'Samim',
    fontWeight: 'bold',
    fontSize: 26,
  },
  suggestionSuccessfullyImage: {
    height: '100%',
    width: '100%',
    resizeMode: 'stretch',
    borderTopRightRadius: 75,
    borderBottomLeftRadius: 75,
  },
});
