import {StyleSheet} from 'react-native';
import Colors from '../colors';

export default StyleSheet.create({
  rectangleOfTop: {
    backgroundColor: Colors.topColor(),
    width: '120%',
    height: '28%',
    transform: [{rotate: '-22deg'}],
    borderBottomLeftRadius: 75,
    position: 'absolute',
    left: '-7%',
    top: '-18%',
    borderWidth: 1,
    borderColor: 'black',
  },
  rectangleOfBottom: {
    backgroundColor: Colors.topColor(),
    width: '120%',
    height: '28%',
    transform: [{rotate: '-22deg'}],
    borderTopRightRadius: 75,
    position: 'absolute',
    right: '-7%',
    bottom: '-18%',
    borderWidth: 1,
    borderColor: 'black',
  },
  square: {
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginTop: '43%',
    width: '80.8%',
    height: '37.3%',
    borderWidth: 2,
    borderColor: Colors.topColor(),
    borderRadius: 25,
    marginBottom: '6%',
  },
  styleOfImage: {
    width: '28%',
    height: '17%',
    resizeMode: 'stretch',
  },
  contactTextStyle: {
    fontFamily: 'IranSans',
    fontSize: 17,
    color: 'rgb(57,62,70)',
  },
  contactEmailStyle: {
    fontFamily: 'Samim',
    fontWeight: 'bold',
    fontSize: 20,
    color: 'rgb(34,40,49)',
  },
  contactUsStyle: {flex: 1, alignItems: 'center'},
  topPartOfSuggestionPage: {
    height: '10%',
    width: '100%',
    backgroundColor: Colors.topColor(),
    borderBottomRightRadius: 100,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderColor: Colors.borderTopColor(),
  },
  bottomPartOfSuggestionPage: {
    borderWidth: 1,
    borderColor: Colors.borderTopColor(),
    position: 'absolute',
    bottom: 0,
    height: '10%',
    width: '100%',
    backgroundColor: Colors.topColor(),
    borderTopLeftRadius: 100,
  },
  suggestionBackgroundImage: {
    width: '100%',
    height: '90%',
    resizeMode: 'stretch',
    alignItems: 'center',
  },
  textOfSuggestion: {
    fontFamily: 'IranSans',
    marginLeft: '60%',
    fontSize: 25,
    marginTop: '26%',
  },
  animatedTextStyle: {
    color: Colors.accent(),
    fontFamily: 'Samim',
    fontWeight: 'bold',
    fontSize: 26,
  },
  suggestionSuccessfullyImage: {
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'black',
    height: '100%',
    width: '100%',
    resizeMode: 'stretch',
    borderTopRightRadius: 75,
    borderBottomLeftRadius: 75,
  },
  changePasswordStyle: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backgroundStyleOfChangePassword: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
  },
  imageStyleOfChangePassword: {
    width: '26%',
    height: '15%',
    resizeMode: 'stretch',
    marginTop: '10%',
  },
  topPartOfChangePassword: {
    height: '10%',
    width: '100%',
    backgroundColor: Colors.topColor(),
    borderBottomWidth: 0.5,
    borderBottomColor: Colors.borderTopColor(),
  },
  textStyleOfChangePassword: {
    fontFamily: 'Samim',
    fontWeight: 'bold',
    color: Colors.accent(),
    opacity: 0.4,
    fontSize: 15,
    marginBottom: '3%',
  },
  bottomPartOfChangePassword: {
    position: 'absolute',
    bottom: 0,
    height: '10%',
    width: '100%',
    backgroundColor: Colors.topColor(),
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    borderWidth: 1,
    borderColor: Colors.borderTopColor(),
  },
  warningTextStyle: {
    color: 'red',
    fontFamily: 'Samim',
    fontWeight: 'bold',
    fontSize: 15,
  },
  topPartOfForgetPassword: {
    height: '12%',
    width: '100%',
    backgroundColor: Colors.topColor(),
    borderBottomRightRadius: 100,
    borderBottomWidth: 1,
    borderRightWidth: 1,
    borderColor: Colors.borderTopColor(),
  },
  forgetPasswordStyle: {
    backgroundColor: Colors.backgroundColor(),
    flex: 1,
    alignItems: 'center',
  },
  bottomPartOfForgetPassword: {
    borderWidth: 1,
    marginTop: '8%',
    alignItems: 'center',
    width: '100%',
    height: '40%',
    backgroundColor: Colors.topColor(),
    borderTopRightRadius: 75,
    borderTopLeftRadius: 75,
  },
  forgetPasswordImage: {
    width: '28%',
    resizeMode: 'stretch',
    height: '16%',
    marginTop: '15%',
  },
  forgetPasswordText: {
    marginTop: '7%',
    opacity: 0.7,
    color: 'rgb(57,62,70)',
    fontFamily: 'Samim-Bold',
    fontSize: 15,
  },
});
